set(_NETCDF 1)
add_compile_definitions(_NUMERIC_MODE=1)
add_compile_definitions(_ONLY_RECT=1)
add_compile_definitions(_PROFILE_MODE=0)
add_compile_definitions(_DISABLE_WET_DRY=0)
add_compile_definitions(_CALCULATE_Q_MODE=1)
add_compile_definitions(_SGM_BY_BLOCKS=0)
add_compile_definitions(_BALANCE_TYPE=0)
